dist: bionic
language: python
python:
    - "2.7"
    - "3.7"
    - "3.8"
install:
    - pip install flake8 pyflakes
script:
    - echo "Checking Scripts using shellcheck"
    - for f in *.sh; do echo ""; echo "Checking $f"; shellcheck "$f"; done
    - echo ""
    - echo "Running 'check.sh' script"
    - bash check.sh
