os: linux
arch: arm64
dist: bionic
language: python
git:
  depth: false
python:
  - "2.7"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install flake8 pyflakes
script:
  - echo "Running 'check.sh' script" && bash check.sh
jobs:
  include:
    - stage: "Adding executables"
      language: bash
      script: echo "DOES NOTHING"
