os: linux
dist: bionic
language: python
cache: pip
git:
  depth: false
python:
  - "2.7"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - echo "Running 'check.sh' script" && bash check.sh
jobs:
  include:
    - stage: "Adding executable permission"
      language: shell
      script: |
        bash make_executable.sh
