os: linux
dist: focal
language: python
cache: pip
git:
  depth: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - echo "Running 'check.sh' script"
  - bash check.sh
  - py.test --verbose
jobs:
  include:
    - stage: "Adding executable permission"
      language: shell
      script: |
        bash make_executable.sh
