version: 2
jobs:
  build:
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run:
          name: Getting Python & PIP Ready
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Python Version Info
          command: python --version
      - run:
          name: Check Python Programs
          command: bash check.sh
      - run:
          name: Run Tests
          command: py.test --verbose
