version: 2
jobs:
  build:
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run:
          name: Getting Python & PIP Ready
          command: 'pip install --upgrade pip && pip install flake8 pyflakes'
      - run: 
          name: Checking Python Programs using Pyflakes & Flake8
          command: bash check.sh
