version: 2
jobs:
  build:
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run:
          name: Getting Environment Ready
          command: |
            pip install --upgrade pip 1> /dev/null
            pip install pipenv 1> /dev/null
            pipenv install --system
      - run:
          name: Python Version Info
          command: python --version
      - run:
          name: Check Python Programs
          command: bash check.sh
      - run:
          name: Run Tests
          command: py.test --verbose
