version: 2
jobs:
  build:
    docker:
      - image: "python:latest"
    steps:
      - checkout
      - run:
          name: Getting Python & PIP Ready
          command: 'apt-get update && apt-get install -y && pip install flake8 pyflakes'
      - run:
          name: Checking Python Programs using Flake8
          command: 'flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics'
      - run: 
          name: Checking Python Programs using Pyflakes
          command: bash check.sh
