name: Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: "ubuntu-latest"

    container: crazyuploader/python_build_tools:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip 1> /dev/null
          pip install pipenv 1> /dev/null
          pipenv install --system

      - name: Check Python Programs
        run: |
          bash check.sh

      - name: Run Tests
        run: |
          py.test --verbose
